/* Source-preserving portfolio editor. Unchanged exports return the original bytes. */
(function(root){
'use strict';
const C=root.PortfolioBuilderCore,clone=x=>JSON.parse(JSON.stringify(x)),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),E=C.escape,L=C.lines;
const parse=s=>new DOMParser().parseFromString(s,'text/html');
const serialize=d=>'<!doctype html>\n'+d.documentElement.outerHTML;
const sectionNames={home:'Hero',about:'About',journey:'Journey',research:'Research',papers:'Papers',teaching:'Teaching',resources:'Teaching PDFs',exploration:'Exploration',mathematics:'Mathematical notes',projects:'Selected projects'};
const fonts={original:'Keep current font',cm:'Computer Modern',system:'System sans-serif',Arial:'Arial',Helvetica:'Helvetica',Verdana:'Verdana',Tahoma:'Tahoma',Trebuchet:'Trebuchet MS',Segoe:'Segoe UI',Calibri:'Calibri',Aptos:'Aptos',Candara:'Candara',Corbel:'Corbel',Georgia:'Georgia',Times:'Times New Roman',Cambria:'Cambria',Constantia:'Constantia',Garamond:'Garamond',Palatino:'Palatino Linotype',BookAntiqua:'Book Antiqua',Baskerville:'Baskerville',Didot:'Didot',Courier:'Courier New',Consolas:'Consolas',Lucida:'Lucida Console',Impact:'Impact',Franklin:'Franklin Gothic Medium'};
function fontCSS(k){if(k==='cm')return '"Computer Modern",serif';if(k==='system')return 'system-ui,sans-serif';return '"'+(fonts[k]||'Arial')+'",'+(['Georgia','Times','Cambria','Constantia','Garamond','Palatino','BookAntiqua','Baskerville','Didot'].includes(k)?'serif':/Courier|Consolas|Lucida/.test(k)?'monospace':'sans-serif');}
function readState(source){const m=source.match(/<script\b[^>]*\bid=["']portfolio-builder-state["'][^>]*>([\s\S]*?)<\/script>/i);if(!m)throw Error('This page does not contain portfolio design data. Choose the portfolio folder supplied with this builder.');const s=JSON.parse(m[1]);if(!s.profile||!s.hero||!Array.isArray(s.projects))throw Error('The page contains incomplete portfolio design data.');return s;}
function inferExtra(source){const d=parse(source),saved=d.getElementById('portfolio-studio-state');if(saved){const x=JSON.parse(saved.textContent);if(x.version!==2)throw Error('Unsupported builder settings version.');return x;}
 const nav=Array.from(d.querySelectorAll('header nav a')).map(a=>({label:a.textContent,href:a.getAttribute('href'),enabled:true}));
 const sections=Array.from(d.querySelectorAll('main > section[id]')).map(n=>({id:n.id,label:sectionNames[n.id]||n.id,enabled:!n.hidden,background:'',padding:0}));
 for(const id of Object.keys(sectionNames))if(!sections.some(x=>x.id===id))sections.push({id,label:sectionNames[id],enabled:false,background:'',padding:0});
 const badge=d.querySelector('#visit-counter img');let endpoint=badge?.getAttribute('data-counter-src')||'',label='Page visits',color='f4c4ad',labelColor='090a0d';try{const u=new URL(endpoint);label=u.searchParams.get('label')||label;color=u.searchParams.get('color')||color;labelColor=u.searchParams.get('labelColor')||labelColor;}catch{}
 return {version:2,fonts:{body:'original',headings:'original'},layout:{heroAlign:'original',heroHeight:0,lineHeight:0,cornerRadius:0,cardBorder:1,headerPosition:'original',imageRatio:'1 / 1',imageFit:'cover',cardShadow:0},sections,navigation:nav,motion:{enabled:true,autoplay:true,showButton:true,showRipple:true},counter:{enabled:!!badge,endpoint,label,color:'#'+color,labelColor:'#'+labelColor,align:'original',style:'flat',height:20},seo:{homeTitle:d.title,projectsTitle:'Projects — '+readState(source).profile.name,canonical:'',socialTitle:'',socialDescription:'',socialImage:'',favicon:'',robots:'index,follow'},customCSS:'',customSections:[]};
}
function validate(s,x){if(!s||s.schemaVersion!==1)throw Error('Invalid design file.');for(const[k,v]of Object.entries(s.theme))if(!/^#[0-9a-f]{6}$/i.test(v))throw Error('Choose a valid six-digit color for '+k+'.');for(const group of ['sizes','motion'])for(const[k,v]of Object.entries(s[group]||{}))if(!Number.isFinite(v)||v<0||v>1000)throw Error('Invalid '+k+' setting.');
 const valid=v=>!v||/^(mailto:|tel:)/i.test(v)||C.safeUrl(v);
 function walk(o,path=''){if(Array.isArray(o)){if(o.length>200)throw Error('Keep each list under 200 items.');o.forEach(v=>walk(v,path));}else if(o&&typeof o==='object')for(const[k,v]of Object.entries(o)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Unsupported field.');if(typeof v==='string'&&/^(url|href|preview|image|sourceUrl|tributeUrl|endpoint|canonical|socialImage|favicon)$/.test(k)&&!valid(v))throw Error('Check the link in '+path+'.'+k);walk(v,path+'.'+k);}}
 walk(s);walk(x);for(const item of s.mathematics.items)if(item.enabled)C.mathML(item.latex);if(x.customCSS.toLowerCase().includes('</style'))throw Error('Custom CSS must contain CSS only.');return true;}
function head(s){return '<div class="section-head"><div class="eyebrow">'+E(s.eyebrow)+'</div><h2>'+L(s.heading)+'</h2></div>';}
const link=(url,text,cls='')=>'<a class="'+cls+'" href="'+E(url)+'" target="_blank" rel="noopener noreferrer">'+text+'</a>';
function project(p){return '<article class="project-card">'+(p.image?link(p.url,'<img class="project-image" src="'+E(p.image)+'" alt="'+E(p.imageAlt||p.name)+'" loading="lazy">','project-image-link'):'')+'<div class="project-meta"><span>'+E(p.category)+'</span><span class="project-mark" aria-hidden="true">'+E(p.mark)+'</span></div><h3>'+E(p.name)+'</h3><p>'+E(p.description)+'</p><p class="project-feature">'+E(p.features)+'</p>'+link(p.url,'Open project <span aria-hidden="true">↗</span>','text-link')+'<small>'+E(p.note)+'</small></article>';}
function documentCard(p){return '<article class="document-card">'+link(p.url,'<span class="frame-caption"><span>'+E(p.category)+'</span><span>PDF / '+E(p.pages)+' pages</span></span><span class="paper-mat"><img src="'+E(p.preview)+'" alt="'+E(p.title)+' preview" loading="lazy" width="742" height="960"></span><span class="frame-open">Open the document ↗</span>','paper-frame')+'<div class="document-copy"><div class="eyebrow">'+E(p.meta)+'</div><h3>'+link(p.url,E(p.title))+'</h3><p>'+E(p.description)+'</p><a class="text-link" href="'+E(p.url)+'" download>Download PDF ↓</a></div></article>';}
function equation(e,i){return '<article class="equation-card" style="--equation-multiplier:'+((e.scale||100)/100)+'"><div class="equation-meta"><span>'+E(e.label)+'</span><span>'+String(i+1).padStart(2,'0')+'</span></div><h3>'+E(e.title)+'</h3><div class="equation" tabindex="0" role="region" aria-label="Equation for '+E(e.title)+'">'+C.mathML(e.latex)+'</div><p>'+E(e.description)+'</p><details class="equation-notes"><summary>Inside the equation <span aria-hidden="true">+</span></summary><div><p>'+E(e.notation)+'</p>'+link(e.sourceUrl,E(e.sourceLabel)+' ↗')+'</div></details></article>';}
function research(r,i){return '<details'+(i===0?' open':'')+'><summary><span class="number">'+String(i+1).padStart(2,'0')+'</span><h3>'+E(r.title)+'<small>'+E(r.subtitle)+'</small></h3><span class="plus" aria-hidden="true">+</span></summary><div class="detail"><p>'+E(r.description)+'</p><div class="research-notes">'+r.notes.map(n=>'<div><h4>'+E(n.heading)+'</h4><p>'+E(n.text)+'</p></div>').join('')+'</div><div class="tags">'+r.tags.map(t=>'<span>'+E(t)+'</span>').join('')+'</div></div></details>';}
function course(c){return '<article class="course"><div class="eyebrow">'+E(c.code)+'</div><h3>'+E(c.name)+'</h3><p>'+E(c.description)+'</p><details><summary>Explore the course themes <span class="plus" aria-hidden="true">+</span></summary><div class="detail"><ol>'+c.topics.map(t=>'<li>'+E(t)+'</li>').join('')+'</ol></div></details></article>';}
function journey(j){return '<li class="timeline-item"><div class="timeline-date">'+E(j.year)+'</div><article class="timeline-card"><div class="eyebrow">'+E(j.category)+'</div><h3>'+E(j.title)+'</h3><p class="timeline-organization">'+E(j.organization)+'</p><p class="timeline-location">'+E(j.location)+'</p><p class="timeline-description">'+E(j.description)+'</p></article></li>';}
function putStyle(d,id,css){let n=d.getElementById(id);if(!n){n=d.createElement('style');n.id=id;d.head.append(n);}n.textContent=css;}
function putScriptJSON(d,id,value){let n=d.getElementById(id);if(!n){n=d.createElement('script');n.type='application/json';n.id=id;d.body.append(n);}n.textContent=C.json(value);}
function sizesCSS(s){const v=s.sizes,f=k=>(v[k]||100)/100,body=f('body'),hero=f('hero'),heading=f('headings'),card=f('cardTitles'),label=f('labels'),pad=f('tilePadding'),gap=f('gridGap'),sp=f('sectionSpacing'),pdf=f('pdfHeight'),math=f('equations'),side=(100-v.contentWidth)/2;
 return `html{font-size:${f('overall')*16}px}body{font-size:${1.0625*body}rem}h1{font-size:clamp(${4*hero}rem,${8.7*hero}vw,${8.875*hero}rem)}.projects-intro h1{font-size:clamp(${3.75*hero}rem,${8*hero}vw,${7*hero}rem)}h2{font-size:clamp(${2.25*heading}rem,${4.7*heading}vw,${4.625*heading}rem)}.project-card h3{font-size:${2*card}rem}.document-copy h3{font-size:${1.9375*card}rem}.resources .document-copy h3{font-size:${1.625*card}rem}.equation-card h3{font-size:${1.6875*card}rem}.intro,.section-intro{font-size:${1.1875*body}rem}.bio-note{font-size:${1.125*body}rem}.project-card p{font-size:${1.0625*body}rem}.research-notes p,.course .detail,.document-copy p,.equation-card>p,.timeline-description{font-size:${body}rem}.eyebrow,footer,.project-card small,.motion{font-size:${.8125*label}rem}nav,.credentials,.section-nav,.semester,summary small,.course summary,.research-notes h4,.back-link,.ripple-button{font-size:${.875*label}rem}.tags span,.project-meta,.interaction-hint,.signal-label,.frame-caption,.frame-open,.document-copy .eyebrow,.equation-meta,.equation-notes a{font-size:${.75*label}rem}.brand{font-size:${1.25*label}rem}.section{padding:${6.875*sp}rem ${side}vw}.hero{padding-inline:${side}vw}.projects-intro{padding-inline:${side}vw}.teaching{margin-inline:${Math.max(0,side-2)}vw;padding-inline:2vw}.project-grid{grid-template-columns:repeat(${v.projectColumns},minmax(0,1fr));gap:${1.625*gap}rem}.papers .document-grid{grid-template-columns:repeat(${v.paperColumns},minmax(0,1fr))}.resources .document-grid{grid-template-columns:repeat(${v.resourceColumns},minmax(0,1fr))}.equation-grid{grid-template-columns:repeat(${v.equationColumns},minmax(0,1fr));gap:${1.625*gap}rem}.document-grid{gap:${4*gap}rem ${2.375*gap}rem}.project-card{padding:${2.125*pad}rem}.equation-card{padding:${1.875*pad}rem}.paper-mat{height:${27.5*pdf}rem}.resources .paper-mat{height:${21.875*pdf}rem}.equation-card .equation math{font-size:calc(${1.875*math}rem * var(--equation-multiplier,1))}.equation-card:first-child .equation math{font-size:calc(${1.5625*math}rem * var(--equation-multiplier,1))}@media(max-width:1100px){.project-grid,.papers .document-grid,.resources .document-grid,.equation-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){h1{font-size:clamp(${3*hero}rem,${12.5*hero}vw,${5.625*hero}rem)}h2{font-size:clamp(${2*heading}rem,${8*heading}vw,${3*heading}rem)}.section{padding-block:${4.375*sp}rem}.project-grid,.papers .document-grid,.resources .document-grid,.equation-grid{grid-template-columns:1fr}.equation-card .equation math,.equation-card:first-child .equation math{font-size:calc(${1.4375*math}rem * var(--equation-multiplier,1))}}`;
}
function extrasCSS(x){let css='';const l=x.layout;if(x.fonts.body!=='original')css+='body,button,input,textarea,select{font-family:'+fontCSS(x.fonts.body)+'}';if(x.fonts.headings!=='original')css+='h1,h1 em,h2,h3,.timeline-date,.footer-name{font-family:'+fontCSS(x.fonts.headings)+'}';if(l.lineHeight)css+='p,li{line-height:'+l.lineHeight+'}';if(l.heroAlign!=='original')css+='.hero-content{text-align:'+l.heroAlign+';'+(l.heroAlign==='center'?'margin-inline:auto;':'')+'}.hero-content .intro{'+(l.heroAlign==='center'?'margin-inline:auto;':'')+'}';if(l.heroHeight)css+='.hero{min-height:'+l.heroHeight+'svh}';if(l.headerPosition!=='original')css+='header{position:'+l.headerPosition+';top:0}';
 css+='.project-card,.paper-frame,.equation-card,.timeline-card{border-radius:'+l.cornerRadius+'px;border-width:'+l.cardBorder+'px}';if(l.cardShadow)css+='.project-card,.paper-frame,.equation-card,.timeline-card{box-shadow:0 10px '+l.cardShadow+'px #0005}';
 css+='.project-image-link{display:block}.project-image{display:block;width:100%;aspect-ratio:'+l.imageRatio+';object-fit:'+l.imageFit+';border-radius:'+l.cornerRadius+'px;margin-bottom:22px}.builder-custom-section img{display:block;width:100%;max-height:550px;object-fit:contain;margin-block:24px}.builder-custom-section p{white-space:pre-line;color:var(--muted)}[data-builder-hidden=true]{display:none!important}';
 if(!x.motion.enabled)css+='#field,#signal,.signal-actions,#motion{display:none!important}';if(!x.motion.showButton)css+='#motion{display:none!important}';if(!x.motion.showRipple)css+='#ripple,.interaction-hint{display:none!important}';
 for(const a of x.sections){if(!/^[\w-]+$/.test(a.id))continue;if(a.background)css+='#'+a.id+'{background:'+a.background+'}';if(a.padding)css+='#'+a.id+'{padding-block:'+a.padding+'px}';}
 return css;
}
function changedContent(d,s,b,page){
 const text=(sel,value)=>d.querySelectorAll(sel).forEach(n=>n.textContent=value),html=(sel,value)=>d.querySelectorAll(sel).forEach(n=>n.innerHTML=value);
 const patch=(now,old,key,sel,br=false)=>{if(!eq(now[key],old[key]))(br?html:text)(sel,br?L(now[key]):now[key]);};
 patch(s.profile,b.profile,'name','.brand,.footer-name');if(s.profile.name!==b.profile.name)d.title=d.title.replace(b.profile.name,s.profile.name);patch(s.profile,b.profile,'footerLine','footer > div:first-child p');patch(s.profile,b.profile,'independence','footer > div:nth-child(2) > p:first-child');
 if(!eq(s.profile.description,b.profile.description)){let m=d.querySelector('meta[name=description]');if(!m){m=d.createElement('meta');m.name='description';d.head.append(m);}m.content=s.profile.description;}
 if(!eq(s.profile.name,b.profile.name)||!eq(s.profile.degree,b.profile.degree))html('#about .bio-grid > .eyebrow',E(s.profile.name)+'<br>'+E(s.profile.degree));
 if(!eq(s.profile.tributeLabel,b.profile.tributeLabel)||!eq(s.profile.tributeUrl,b.profile.tributeUrl))html('footer > div:nth-child(2) > p:nth-child(2)','With appreciation for '+link(s.profile.tributeUrl,E(s.profile.tributeLabel))+'.');
 if(page==='home'){
 for(const id of ['about','research','teaching','exploration','papers','resources','mathematics','journey','featured']){const a=s[id],z=b[id];if(!a||!z)continue;const dom=id==='featured'?'projects':id;patch(a,z,'eyebrow','#'+dom+(dom==='exploration'?' > div > .eyebrow':' > .section-head > .eyebrow'));patch(a,z,'heading','#'+dom+' h2',true);if(a.intro!==undefined)patch(a,z,'intro','#'+dom+' > .section-intro');}
 patch(s.hero,b.hero,'eyebrow','#home .hero-content > .eyebrow');patch(s.hero,b.hero,'intro','#home .intro');if(['line1','line2','emphasis'].some(k=>s.hero[k]!==b.hero[k]))html('#home h1',E(s.hero.line1)+'<br>'+E(s.hero.line2)+' <em>'+E(s.hero.emphasis)+'</em>');if(s.hero.cta!==b.hero.cta)html('#home .hero-bottom > .text-link',E(s.hero.cta)+' <span aria-hidden="true">↓</span>');
 if(s.about.lead!==b.about.lead||s.about.secondary!==b.about.secondary)html('#about .about-copy',E(s.about.lead)+' <span>'+E(s.about.secondary)+'</span>');patch(s.about,b.about,'note','#about .bio-note');if(!eq(s.about.institutions,b.about.institutions))html('#about .credentials',s.about.institutions.map(a=>'<div><strong>'+E(a.title)+'</strong>'+E(a.subtitle)+'</div>').join(''));
 if(!eq(s.research.items,b.research.items))html('#research .research-list',s.research.items.filter(a=>a.enabled!==false).map(research).join(''));
 if(!eq(s.journey.items,b.journey.items))html('#journey .timeline-list',s.journey.items.filter(a=>a.enabled!==false).map(journey).join(''));
 if(s.journey.sourceLabel!==b.journey.sourceLabel||s.journey.sourceUrl!==b.journey.sourceUrl){const sec=d.getElementById('journey');if(sec){sec.querySelector('.journey-source')?.remove();if(s.journey.sourceLabel&&s.journey.sourceUrl)sec.insertAdjacentHTML('beforeend',link(s.journey.sourceUrl,E(s.journey.sourceLabel),'text-link journey-source'));}}
 if(!eq(s.teaching.courses,b.teaching.courses))html('#teaching .courses',s.teaching.courses.filter(a=>a.enabled!==false).map(course).join(''));patch(s.teaching,b.teaching,'intro','#teaching .teaching-intro');patch(s.teaching,b.teaching,'semester','#teaching .semester');
 if(!eq(s.exploration.paragraphs,b.exploration.paragraphs)){const n=d.querySelector('#exploration > div');if(n){n.querySelectorAll(':scope > p').forEach(a=>a.remove());const after=n.querySelector('h2');after?.insertAdjacentHTML('afterend',s.exploration.paragraphs.map(p=>'<p>'+E(p)+'</p>').join(''));}}
 if(!eq(s.mathematics.items,b.mathematics.items))html('#mathematics .equation-grid',s.mathematics.items.filter(e=>e.enabled).map(equation).join(''));
 if(!eq(s.documents,b.documents))for(const[id,kind]of [['papers','paper'],['resources','resource']]){const content=s.documents.filter(a=>a.enabled&&a.kind===kind).map(documentCard).join('');let sec=d.getElementById(id);if(!sec&&content){sec=d.createElement('section');sec.id=id;sec.className='section document-section '+id;sec.innerHTML=head(s[id])+'<p class="section-intro">'+E(s[id].intro)+'</p><div class="document-grid"></div>';d.querySelector('main').append(sec);}if(sec)sec.querySelector('.document-grid').innerHTML=content;}
 }
 if(page==='projects'){for(const k of ['eyebrow','intro'])if(s.gallery[k]!==b.gallery[k]){if(k==='intro')text('.projects-intro > p',s.gallery.intro);else html('.projects-intro > .eyebrow',E(s.gallery.eyebrow)+' / <span class="project-count">'+s.projects.filter(p=>p.enabled).length+' projects</span>');}if(['line1','line2','emphasis'].some(k=>s.gallery[k]!==b.gallery[k]))html('.projects-intro h1',E(s.gallery.line1)+'<br>'+E(s.gallery.line2)+' <em>'+E(s.gallery.emphasis)+'</em>');}
 if(!eq(s.projects,b.projects)){const active=s.projects.filter(a=>a.enabled),items=page==='home'?active.filter(a=>a.featured):active;html(page==='home'?'#projects .project-grid':'#project-list .project-grid',items.map(project).join(''));html('.projects-footer-link .text-link','View all '+active.length+' projects ↗');text('.project-count',String(active.length).padStart(2,'0')+' projects');}
}
function counter(d,x){const c=x.counter;const old=d.getElementById('visit-counter');if(!c.enabled){old?.remove();return;}let u;try{u=new URL(c.endpoint);if(!/^https?:$/.test(u.protocol))throw Error();}catch{throw Error('Use a complete HTTP(S) counter badge URL.');}u.searchParams.set('label',c.label);u.searchParams.set('color',c.color.slice(1));u.searchParams.set('labelColor',c.labelColor.slice(1));u.searchParams.set('style',c.style);
 const box=d.createElement('div');box.className='visit-counter';box.id='visit-counter';box.setAttribute('aria-live','polite');box.innerHTML='<span class="visit-counter-status">'+E(c.label)+' · offline</span><img data-counter-src="'+E(u.href)+'" alt="'+E(c.label)+'" height="'+c.height+'" referrerpolicy="no-referrer" hidden>';if(old)old.replaceWith(box);else d.querySelector('footer')?.append(box);
 putStyle(d,'builder-counter-style','.visit-counter{flex-basis:100%;display:flex;align-items:center;justify-content:'+(c.align==='original'?'flex-end':c.align)+';padding-top:12px;min-height:24px}.visit-counter [hidden]{display:none}.visit-counter img{height:'+c.height+'px;max-width:100%}.visit-counter-status{font-size:12px;color:var(--muted)}');
 let script=d.getElementById('portfolio-counter-script');if(!script){script=d.createElement('script');script.id='portfolio-counter-script';d.body.append(script);}script.textContent="(()=>{const c=document.getElementById('visit-counter');if(!c)return;const i=c.querySelector('img'),s=c.querySelector('span');if(!i||!/^https?:$/.test(location.protocol))return;s.textContent="+C.json(c.label+' · loading')+";i.onload=()=>{s.hidden=true;i.hidden=false;};i.onerror=()=>{s.textContent="+C.json(c.label+' · unavailable')+";s.hidden=false;i.hidden=true;};i.src=i.dataset.counterSrc;})();";
}
function applyExtra(d,x,b,page,s){
 if(page==='home'){const main=d.querySelector('main');for(const a of x.sections){const n=d.getElementById(a.id);if(!n)continue;n.setAttribute('data-builder-hidden',String(!a.enabled));main.append(n);}}
 if(!eq(x.customSections,b.customSections)&&page==='home'){d.querySelectorAll('.builder-custom-section').forEach(n=>n.remove());for(const a of x.customSections){if(!a.enabled)continue;const n=d.createElement('section');n.className='section builder-custom-section';n.id=a.id;const safeId=/^[\w-]+$/.test(a.id);if(!safeId)throw Error('Custom section IDs can contain only letters, numbers, dashes, and underscores.');n.innerHTML='<div class="eyebrow">'+E(a.eyebrow)+'</div><h2>'+L(a.heading)+'</h2>'+(a.image?'<img src="'+E(a.image)+'" alt="'+E(a.imageAlt||a.heading)+'">':'')+'<p>'+E(a.text)+'</p>'+(a.url?link(a.url,E(a.linkLabel||'Read more'),'text-link'):'');d.querySelector('main').append(n);}}
 if(!eq(x.navigation,b.navigation)||!eq(x.sections,b.sections)){const nav=d.querySelector('header nav');if(nav)nav.innerHTML=x.navigation.filter(a=>a.enabled).filter(a=>{const id=a.href.split('#')[1],sec=x.sections.find(s=>s.id===id);return !sec||sec.enabled;}).map(a=>'<a href="'+E(page==='projects'&&a.href.startsWith('#')?'index.html'+a.href:a.href)+'">'+E(a.label)+'</a>').join('');}
 if(!eq(x.counter,b.counter))counter(d,x);
 if(!eq(x.seo,b.seo)){const seo=x.seo;d.title=page==='home'?seo.homeTitle:seo.projectsTitle;const meta=(key,value,attr='name')=>{let n=d.head.querySelector('meta['+attr+'="'+key+'"]');if(!value){n?.remove();return;}if(!n){n=d.createElement('meta');n.setAttribute(attr,key);d.head.append(n);}n.content=value;};meta('robots',seo.robots);for(const[k,v]of [['og:title',seo.socialTitle],['og:description',seo.socialDescription],['og:image',seo.socialImage]])meta(k,v,'property');for(const[rel,value]of [['icon',seo.favicon],['canonical',seo.canonical]]){let n=d.head.querySelector('link[rel="'+rel+'"]');if(!value)n?.remove();else{if(!n){n=d.createElement('link');n.rel=rel;d.head.append(n);}n.href=rel==='canonical'&&page==='projects'?new URL('projects.html',value).href:value;}}}
 if(['fonts','layout','sections','motion'].some(k=>!eq(x[k],b[k])))putStyle(d,'builder-extra-style',extrasCSS(x));
 // Image CSS is needed even when all layout controls retain their defaults.
 if(s.projects.some(p=>p.image)||x.customSections.some(a=>a.enabled))putStyle(d,'builder-extra-style',extrasCSS(x));
 if(x.customCSS!==b.customCSS)putStyle(d,'builder-custom-css',x.customCSS);
 if(x.motion.autoplay!==b.motion.autoplay){let script=d.getElementById('builder-motion-init');if(!script){script=d.createElement('script');script.id='builder-motion-init';d.body.append(script);}script.textContent=x.motion.autoplay?'':"window.addEventListener('load',()=>{const b=document.getElementById('motion');if(b?.getAttribute('aria-pressed')==='true')b.click();});";}
 // Every hidden section also loses links from the remaining homepage content.
 if(!eq(x.sections,b.sections))d.querySelectorAll('a[href^="#"]').forEach(a=>{const id=a.getAttribute('href').slice(1);const s=x.sections.find(n=>n.id===id);if(s&&!s.enabled)a.setAttribute('data-builder-hidden','true');else if(s)a.removeAttribute('data-builder-hidden');});
}
function render(source,s,x,page='home',preview=null){const b=readState(source),old=inferExtra(source);if(!preview&&eq(s,b)&&eq(x,old))return source;const d=parse(source);changedContent(d,s,b,page);
 if(!eq(s.theme,b.theme)){putStyle(d,'builder-theme-style',C.themeCSS(s.theme));const m=d.querySelector('meta[name=theme-color]');if(m)m.content=s.theme.background;}
 if(!eq(s.sizes,b.sizes))putStyle(d,'builder-size-style',sizesCSS(s));
 if(!eq(s.motion,b.motion))putStyle(d,'builder-signal-style',':root{--signal-dance:'+s.motion.dance/100+';--signal-speed:'+s.motion.speed/100+';--signal-coupling:'+s.motion.coupling/100+';--signal-spacing:'+s.motion.spacing+';--signal-thickness:'+s.motion.thickness/100+';--signal-opacity:'+s.motion.opacity/100+'}');
 applyExtra(d,x,old,page,s);putScriptJSON(d,'portfolio-builder-state',s);putScriptJSON(d,'portfolio-studio-state',x);
 if(preview){d.getElementById('portfolio-counter-script')?.remove();d.querySelectorAll('#visit-counter img').forEach(n=>{n.removeAttribute('src');n.hidden=true;});const status=d.querySelector('.visit-counter-status');if(status){status.hidden=false;status.textContent=x.counter.label+' · preview';}
 for(const img of d.querySelectorAll('img')){const src=img.getAttribute('src');if(preview.previews?.[src])img.setAttribute('src',preview.previews[src]);else if(preview.base&&src&&!/^(https?:|data:|blob:)/i.test(src))img.setAttribute('src',new URL(src,preview.base).href);}
 if(preview.base){const base=d.createElement('base');base.href=preview.base;d.head.prepend(base);}
 const bridge=d.createElement('script');bridge.textContent="window.addEventListener('load',()=>{const a="+C.json(preview.anchor||'')+";if(a)document.getElementById(a)?.scrollIntoView();else scrollTo(0,"+(preview.scrollY||0)+");});addEventListener('scroll',()=>parent.postMessage({type:'studio-scroll',page:"+C.json(page)+",y:scrollY},'*'),{passive:true});document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href')||'';if(h.startsWith('#')){e.preventDefault();document.getElementById(h.slice(1))?.scrollIntoView();return;}e.preventDefault();parent.postMessage({type:'studio-link',href:h},'*');});addEventListener('message',e=>{if(e.source!==parent)return;if(e.data?.type==='studio-jump')document.getElementById(e.data.id)?.scrollIntoView();});";d.body.append(bridge);
 }
 return serialize(d);
}
root.PortfolioStudioEngine={clone,eq,parse,readState,inferExtra,validate,render,fonts,sectionNames,sizesCSS,extrasCSS};
})(globalThis);
