(function(){
'use strict';
const $=id=>document.getElementById(id),G=PortfolioStudioEngine,F=PortfolioFiles,C=PortfolioBuilderCore,clone=G.clone,eq=G.eq,seed=window.PORTFOLIO_DEFAULTS;
if(!seed?.sources){$('preview-status').textContent='Builder defaults are missing. Keep builder-defaults.js beside index-builder.html.';return;}
let sources=clone(seed.sources),state=G.readState(sources.home),extra=G.inferExtra(sources.home),previews={...seed.previews},session=null,pending=new Map(),page='home',width=0,dirty=false,busy=false,timer,toastTimer,draftTimer,scrolls={home:0,projects:0},undo=[],redo=[],checkpoint={state:clone(state),extra:clone(extra)},historyTimer,previewError=null;
const categories=[['identity','Name & hero'],['content','Content & teaching'],['journey','Journey timeline'],['projects','Project tiles & images'],['documents','Papers & teaching PDFs'],['equations','Mathematical notes'],['sections','Sections & navigation'],['colors','Colors & palettes'],['type','Fonts & text sizes'],['layout','Layout & spacing'],['motion','Signal & animation'],['counter','Visit counter'],['advanced','Metadata & custom CSS'],['files','Files, drafts & reset']];
const hints={identity:'Your current name, designation, headline, and introduction.',content:'Edit every paragraph, affiliation, course, and research item. Lists can be extended and reordered.',journey:'Add, duplicate, reorder, or hide chapters of your timeline.',projects:'Keep existing apps, change links, and upload square tile images or HTML apps.',documents:'Upload PDFs and their preview images. Existing PDF files stay in place.',equations:'Edit LaTeX, explanations, notation, sources, and each equation’s scale.',sections:'Order and visibility start from your current page. Navigation labels and links are editable.',colors:'The original palette is loaded. Every color can be set individually.',type:'Computer Modern is embedded in the portfolio. Other fonts use your installed fonts with a fallback.',layout:'Independent size, column, spacing, image, and card controls.',motion:'Your current mathematical signal settings are loaded.',counter:'Keeps your existing shared hits.sh counter. Previews never count as visits.',advanced:'Page titles, search metadata, a favicon, social preview, and custom CSS.',files:'Save changes to the selected folder, or download an update ZIP.'};
const labelMap={name:'Name',degree:'Degree / designation',description:'Description',footerLine:'Footer line',independence:'Website description',tributeLabel:'Tribute label',tributeUrl:'Tribute URL',eyebrow:'Section / role label',line1:'Headline · first line',line2:'Headline · second line',emphasis:'Headline · italic words',intro:'Introduction',cta:'Explore button label',heading:'Heading',lead:'Opening paragraph',secondary:'Second paragraph',note:'Visitor note',institutions:'Affiliations',title:'Title',subtitle:'Subtitle',items:'Items',notes:'Details',tags:'Tags',semester:'Semester / institution',code:'Course code / credit hours',courses:'Courses',topics:'Topics',paragraphs:'Paragraphs',featured:'Feature on homepage',enabled:'Show on the website',url:'Link',image:'Tile image path / URL',imageAlt:'Image description',preview:'PDF preview image path / URL',mark:'Short visual mark',category:'Category',features:'Features',kind:'Gallery',pages:'Page count',meta:'Authors / context',latex:'Equation · LaTeX',notation:'Variables and conditions',sourceLabel:'Source label',sourceUrl:'Source URL',scale:'Equation size (%)',year:'Year / period',organization:'Organization',location:'Location',text:'Text',linkLabel:'Link label',id:'Stable ID'};
const numberSpecs={overall:['Overall scale (%)',70,150],body:['Paragraph size (%)',60,180],hero:['Hero headline (%)',35,150],headings:['Section headings (%)',50,160],cardTitles:['Card titles (%)',60,160],labels:['Labels & navigation (%)',75,160],equations:['All equation sizes (%)',60,180],tilePadding:['Card padding (%)',40,180],pdfHeight:['PDF preview height (%)',50,160],sectionSpacing:['Section spacing (%)',30,170],gridGap:['Grid gaps (%)',30,180],contentWidth:['Content width (%)',60,96],projectColumns:['Project columns',1,4],paperColumns:['Paper columns',1,4],resourceColumns:['Resource columns',1,4],equationColumns:['Equation columns',1,3],dance:['Movement strength (%)',0,100],speed:['Animation speed (%)',25,180],coupling:['Mouse response (%)',0,200],spacing:['Signal strand spacing',4,10],thickness:['Signal line thickness (%)',50,150],opacity:['Signal visibility (%)',40,160]};
const templates={projects:{id:'project',name:'New project',category:'Project',mark:'↗',description:'',features:'',note:'',url:'',image:'',imageAlt:'',enabled:true,featured:true},documents:{id:'document',title:'New document',kind:'paper',category:'Paper',meta:'',description:'',pages:'',url:'',preview:'',enabled:true},'mathematics.items':{id:'equation',title:'New equation',label:'',latex:'y = x',description:'',notation:'',sourceLabel:'',sourceUrl:'',enabled:true,scale:100},'journey.items':{year:'2026',category:'',title:'New chapter',organization:'',location:'',description:'',enabled:true},'research.items':{title:'New research item',subtitle:'',description:'',notes:[{heading:'The question',text:''}],tags:[],enabled:true},'teaching.courses':{code:'',name:'New course',description:'',topics:[],enabled:true},'about.institutions':{title:'New affiliation',subtitle:''}};
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function get(path){return path.split('.').reduce((a,k)=>a?.[k],path.startsWith('extra.')?{extra}:state);}
function set(path,value){const parts=path.split('.'),last=parts.pop();let obj=path.startsWith('extra.')?{extra}:state;for(const p of parts)obj=obj[p];obj[last]=value;}
function snapshot(){return {state:clone(state),extra:clone(extra)};}
function record(){const now=snapshot();if(!eq(now,checkpoint)){undo.push(checkpoint);undo=undo.slice(-35);checkpoint=now;redo=[];}buttons();}
function buttons(){$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;}
function changed(immediate=false){dirty=true;$('draft-status').textContent='Unsaved folder changes';clearTimeout(historyTimer);if(immediate)record();else historyTimer=setTimeout(record,650);clearTimeout(timer);timer=setTimeout(renderPreview,220);clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,1000);}
function mutate(fn){record();fn();changed(true);renderFields();}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.onclick=fn;return b;}
function group(title,parent,open=false){const d=el('details','group');d.open=open;d.append(el('summary','',title));const body=el('div','group-content');d.append(body);parent.append(d);return body;}
function field(parent,path,label,options={}){
 let value=get(path);if(value===undefined)value=options.default??'';
 const wrap=el('label','field');wrap.dataset.search=(label+' '+path).toLowerCase();const caption=el('span','',label);wrap.append(caption);
 let input;
 if(options.choices){input=el('select');for(const[v,n]of Object.entries(options.choices)){const o=el('option','',n);o.value=v;input.append(o);}input.value=String(value);input.onchange=()=>{set(path,options.numeric?Number(input.value):input.value);if(/^documents\.\d+\.kind$/.test(path)){const id=input.value==='paper'?'papers':'resources';const sec=extra.sections.find(s=>s.id===id);if(sec)sec.enabled=true;}changed();};wrap.append(input);}
 else if(typeof value==='boolean'){wrap.classList.add('check');input=el('input');input.type='checkbox';input.checked=value;input.onchange=()=>{set(path,input.checked);changed();};wrap.prepend(input);}
 else if(options.range){const row=el('div','range-row');input=el('input');input.type='range';const num=el('input');num.type='number';for(const n of [input,num]){n.min=options.range[0];n.max=options.range[1];n.step=options.step||1;n.value=value;n.setAttribute('aria-label',label);}
 const update=(src,dst)=>{const n=Number(src.value);if(!Number.isFinite(n)||n<Number(src.min)||n>Number(src.max)){src.setAttribute('aria-invalid','true');return;}src.removeAttribute('aria-invalid');dst.value=n;set(path,n);changed();};input.oninput=()=>update(input,num);num.oninput=()=>update(num,input);row.append(input,num);wrap.append(row);}
 else if(options.color){const row=el('div','color-row');input=el('input');input.type='color';input.value=value||'#090a0d';const hex=el('input');hex.type='text';hex.value=value;hex.placeholder=options.optional?'Keep current background':'#090a0d';hex.setAttribute('aria-label',label+' hex');input.oninput=()=>{hex.value=input.value;set(path,input.value);changed();};hex.oninput=()=>{const v=hex.value.trim(),valid=/^#[0-9a-f]{6}$/i.test(v)||(options.optional&&v==='');hex.setAttribute('aria-invalid',String(!valid));if(valid){set(path,v);if(v)input.value=v;changed();}};row.append(input,hex);wrap.append(row);}
 else{const multi=options.multiline||Array.isArray(value)||/description|intro|note|notation|paragraph|heading|secondary|lead|customCSS|latex|\.text$/.test(path);input=el(multi?'textarea':'input');if(!multi)input.type=typeof value==='number'?'number':'text';input.value=Array.isArray(value)?value.join('\n'):value;if(options.code)input.className='code';input.oninput=()=>{let v=Array.isArray(value)?input.value.split('\n').map(x=>x.trim()).filter(Boolean):typeof value==='number'?Number(input.value):input.value;set(path,v);changed();};wrap.append(input);}
 if(options.hint)wrap.append(el('small','',options.hint));parent.append(wrap);return input;
}
function assetButton(parent,path,label,accept,folder){const row=el('div','upload');row.append(button(label,()=>{const pick=el('input');pick.type='file';pick.accept=accept;pick.onchange=async()=>{const file=pick.files[0];if(!file)return;try{const clean=file.name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'-').replace(/^-+/,'')||'asset';const dot=clean.lastIndexOf('.'),stem=dot>0?clean.slice(0,dot):clean,ext=dot>0?clean.slice(dot):'';const name=folder+'/'+stem+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)+ext;F.cleanPath(name);pending.set(name,file);if(file.type.startsWith('image/'))previews[name]=await dataURL(file);set(path,name);changed(true);renderFields();toast(file.name+' added. It will be copied into your folder when you save.');}catch(e){toast(e.message);}};pick.click();}));parent.append(row);}
function dataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
function decorateRecord(parent,path,item){
 if(/^(research\.items|teaching\.courses)\.\d+$/.test(path)&&item.enabled===undefined)field(parent,path+'.enabled','Show on the website',{default:true});
 if(/^projects\.\d+$/.test(path)){field(parent,path+'.image','Tile image path / URL',{default:''});field(parent,path+'.imageAlt','Image description',{default:''});const src=previews[item.image]||item.image;if(src){const img=el('img','image-preview');img.src=src;img.alt=item.imageAlt||item.name;parent.append(img);}assetButton(parent,path+'.image','Upload tile image','image/*','media');assetButton(parent,path+'.url','Upload standalone HTML app','.html,.htm','apps/custom');}
 if(/^documents\.\d+$/.test(path)){assetButton(parent,path+'.url','Upload PDF','.pdf,application/pdf','pdfs');assetButton(parent,path+'.preview','Upload preview image','image/*','previews');}
}
function objectFields(parent,path,obj){for(const[k,v]of Object.entries(obj)){if(['image','imageAlt'].includes(k)&&/^projects\.\d+$/.test(path))continue;const p=path?path+'.'+k:k,label=labelMap[k]||k.replace(/([A-Z])/g,' $1');if(Array.isArray(v)){if(v.length&&typeof v[0]==='object')collection(parent,p,label);else if(['items','projects','documents','courses','institutions','notes'].includes(k))collection(parent,p,label);else field(parent,p,label,{multiline:true,hint:'One entry per line.'});}else if(v&&typeof v==='object'){objectFields(group(label,parent),p,v);}else if(k==='kind')field(parent,p,label,{choices:{paper:'Papers & diagrams',resource:'Teaching resources'}});else if(k==='scale')field(parent,p,label,{range:[50,200]});else field(parent,p,label,{multiline:k==='latex'});}decorateRecord(parent,path,obj);}
function collection(parent,path,title){const a=get(path),known=templates[path];a.forEach((item,i)=>{const body=group((i+1)+'. '+(item.name||item.title||item.heading||item.label||title),parent,i===0);const row=el('div','row-tools');const up=button('↑',()=>mutate(()=>[a[i-1],a[i]]=[a[i],a[i-1]]));up.disabled=i===0;const down=button('↓',()=>mutate(()=>[a[i+1],a[i]]=[a[i],a[i+1]]));down.disabled=i===a.length-1;row.append(up,down,button('Duplicate',()=>mutate(()=>{const n=clone(item);if(n.id)n.id+='-'+Date.now().toString(36);a.splice(i+1,0,n);})),button('Remove',()=>mutate(()=>a.splice(i,1)),'danger'));body.append(row);objectFields(body,path+'.'+i,item);});parent.append(button('+ Add '+title.toLowerCase(),()=>mutate(()=>{let item=clone(known||a[0]||{heading:'New detail',text:''});if(!known)for(const[k,v]of Object.entries(item))if(typeof v==='string')item[k]='';if(item.id)item.id+='-'+Date.now().toString(36);a.push(item);}),'add'));}
function sizeFields(parent,keys){for(const k of keys){const[n,min,max]=numberSpecs[k];field(parent,'sizes.'+k,n,{range:[min,max]});}}
function renderFields(){const root=$('fields'),category=$('category').value;root.replaceChildren(el('h2','',categories.find(c=>c[0]===category)[1]),el('p','hint',hints[category]));
 if(category==='identity'){objectFields(group('Name, designation & footer',root,true),'profile',state.profile);objectFields(group('Hero',root,true),'hero',state.hero);}
 if(category==='content'){for(const k of ['about','research','teaching','exploration','featured','gallery','papers','resources'])objectFields(group({about:'About',research:'Research',teaching:'Teaching & courses',exploration:'Exploration',featured:'Selected projects intro',gallery:'Projects page intro',papers:'Papers intro',resources:'Teaching PDFs intro'}[k],root,k==='about'),k,state[k]);}
 if(category==='journey')objectFields(root,'journey',state.journey);
 if(category==='projects')collection(root,'projects','Project');
 if(category==='documents')collection(root,'documents','Document');
 if(category==='equations'){for(const k of ['eyebrow','heading','intro'])field(root,'mathematics.'+k,labelMap[k]);collection(root,'mathematics.items','Equation');}
 if(category==='colors'){const grid=el('div','palette-grid');const palettes=[{name:'Your starting palette',theme:G.readState(sources.home).theme},...C.palettes];for(const p of palettes){const b=button(p.name,()=>mutate(()=>state.theme=clone(p.theme)),'palette');const sw=el('span','swatches');for(const k of ['background','text','accent','signalA','signalB']){const n=el('i');n.style.background=p.theme[k];sw.append(n);}b.prepend(sw);grid.append(b);}root.append(grid);const names={background:'Page background',text:'Main text',muted:'Secondary text',accent:'Accent',signalA:'Signal · first color',signalB:'Signal · second color',panel:'Teaching background',panelText:'Teaching text'};for(const k of Object.keys(names))field(root,'theme.'+k,names[k],{color:true});root.append(button('Match teaching background to page',()=>mutate(()=>{state.theme.panel=state.theme.background;state.theme.panelText=state.theme.text;})));}
 if(category==='type'){field(root,'extra.fonts.body','Body font',{choices:G.fonts});field(root,'extra.fonts.headings','Headings font',{choices:G.fonts});sizeFields(root,['overall','body','hero','headings','cardTitles','labels','equations']);field(root,'extra.layout.lineHeight','Paragraph line height (0 = current)',{range:[0,2.5],step:.05});}
 if(category==='layout'){sizeFields(root,['contentWidth','sectionSpacing','gridGap','tilePadding','pdfHeight','projectColumns','paperColumns','resourceColumns','equationColumns']);field(root,'extra.layout.heroAlign','Hero alignment',{choices:{original:'Keep current',left:'Left',center:'Center',right:'Right'}});field(root,'extra.layout.heroHeight','Hero height (% of viewport; 0 = current)',{range:[0,150]});field(root,'extra.layout.cornerRadius','Card corner radius (px)',{range:[0,40]});field(root,'extra.layout.cardBorder','Card border width (px)',{range:[0,4]});field(root,'extra.layout.cardShadow','Card shadow spread (px)',{range:[0,60]});field(root,'extra.layout.headerPosition','Header position',{choices:{original:'Keep current',sticky:'Sticky',relative:'Scroll with page'}});field(root,'extra.layout.imageRatio','Project image proportions',{choices:{'1 / 1':'Square · 1:1','4 / 3':'Landscape · 4:3','16 / 9':'Wide · 16:9','3 / 4':'Portrait · 3:4'}});field(root,'extra.layout.imageFit','Project image crop',{choices:{cover:'Fill and crop',contain:'Show entire image'}});}
 if(category==='motion'){for(const[k,label]of [['enabled','Show mathematical signal'],['autoplay','Start with motion on'],['showButton','Show motion toggle'],['showRipple','Show ripple controls']])field(root,'extra.motion.'+k,label);for(const k of ['dance','speed','coupling','spacing','thickness','opacity']){const[n,min,max]=numberSpecs[k];field(root,'motion.'+k,n,{range:[min,max]});}}
 if(category==='sections'){extra.sections.forEach((s,i)=>{const body=group((i+1)+'. '+s.label,root);const row=el('div','row-tools');for(const[offset,label]of [[-1,'↑ Up'],[1,'↓ Down']]){const b=button(label,()=>mutate(()=>[extra.sections[i+offset],extra.sections[i]]=[extra.sections[i],extra.sections[i+offset]]));b.disabled=i+offset<0||i+offset>=extra.sections.length;row.append(b);}body.append(row);field(body,'extra.sections.'+i+'.enabled','Show section');field(body,'extra.sections.'+i+'.background','Section background',{color:true,optional:true,hint:'Leave blank to use the page’s existing background.'});field(body,'extra.sections.'+i+'.padding','Vertical padding (px; 0 = current)',{range:[0,220]});});const nav=group('Navigation links',root);extra.navigation.forEach((n,i)=>{const body=group(n.label||'Link',nav);for(const k of ['label','href','enabled'])field(body,'extra.navigation.'+i+'.'+k,{label:'Label',href:'Link or #section',enabled:'Show link'}[k]);const navTools=el('div','row-tools');for(const[offset,label]of [[-1,'↑ Up'],[1,'↓ Down']]){const move=button(label,()=>mutate(()=>[extra.navigation[i+offset],extra.navigation[i]]=[extra.navigation[i],extra.navigation[i+offset]]));move.disabled=i+offset<0||i+offset>=extra.navigation.length;navTools.append(move);}body.append(navTools);body.append(button('Remove link',()=>mutate(()=>extra.navigation.splice(i,1)),'danger'));});nav.append(button('+ Add navigation link',()=>mutate(()=>extra.navigation.push({label:'New link',href:'#home',enabled:true})),'add'));const customs=group('Additional sections',root);extra.customSections.forEach((s,i)=>{const b=group(s.heading||'Custom section',customs);objectFields(b,'extra.customSections.'+i,s);assetButton(b,'extra.customSections.'+i+'.image','Upload section image','image/*','media');b.append(button('Remove section',()=>mutate(()=>extra.customSections.splice(i,1)),'danger'));});customs.append(button('+ Add text / image section',()=>mutate(()=>extra.customSections.push({id:'section-'+Date.now().toString(36),eyebrow:'',heading:'New section',text:'',image:'',imageAlt:'',url:'',linkLabel:'Read more',enabled:true})),'add'));}
 if(category==='counter'){field(root,'extra.counter.enabled','Show shared visit counter');field(root,'extra.counter.endpoint','Counter badge URL',{hint:'Keep the existing URL to preserve the same shared count. A new path starts a different counter.'});field(root,'extra.counter.label','Counter label');field(root,'extra.counter.color','Value background',{color:true});field(root,'extra.counter.labelColor','Label background',{color:true});field(root,'extra.counter.align','Counter alignment',{choices:{original:'Keep current','flex-start':'Left',center:'Center','flex-end':'Right'}});field(root,'extra.counter.style','Badge style',{choices:{flat:'Flat','flat-square':'Flat square','for-the-badge':'Large badge',plastic:'Plastic'}});field(root,'extra.counter.height','Badge height (px)',{range:[16,45]});}
 if(category==='advanced'){for(const[k,label]of [['homeTitle','Homepage title'],['projectsTitle','Projects page title'],['canonical','Canonical URL (optional)'],['socialTitle','Social preview title'],['socialDescription','Social preview description'],['socialImage','Social preview image URL'],['favicon','Favicon path / URL']])field(root,'extra.seo.'+k,label);field(root,'extra.seo.robots','Search indexing',{choices:{'index,follow':'Allow indexing','noindex,nofollow':'Ask search engines not to index'}});assetButton(root,'extra.seo.favicon','Upload favicon','image/*,.ico','media');assetButton(root,'extra.seo.socialImage','Upload social preview image','image/*','media');field(root,'extra.customCSS','Custom CSS',{code:true,multiline:true,hint:'Added after the current styles on both pages. Use #home, #teaching, .project-card, and other existing selectors.'});}
 if(category==='files'){const notice=el('div','notice',session?'Connected to '+session.folder.name+'. Save writes directly here.':'Starting with the supplied pages. Select your portfolio folder to load its latest files and enable direct saving.');root.append(notice);const stack=el('div','action-stack');stack.append(button('Open portfolio folder',openFolder),button('Save to folder',saveFolder,'primary'),button('Download update ZIP',exportZIP),button('Download design JSON',()=>{download('portfolio-design.json',JSON.stringify({...state,_studio:extra},null,2),'application/json');toast('Design downloaded. Uploaded assets are included when you save to a folder or download an update ZIP.');}),button('Open design JSON / exported HTML',()=>$('import-file').click()),button('Restore starting pages',()=>{if(!confirm('Restore the pages currently loaded from your folder or package? You can undo this change.'))return;mutate(()=>{state=G.readState(sources.home);extra=G.inferExtra(sources.home);});}),button('Instructions',()=>$('help-dialog').showModal()));root.append(stack);root.append(el('h3','','Pending uploaded files'));if(!pending.size)root.append(el('p','hint','No new files uploaded.'));else{const list=el('ul','file-list');for(const[path,file]of pending)list.append(el('li','',path+' · '+(file.size/1024).toFixed(0)+' KB'));root.append(list);}root.append(el('p','hint','An update ZIP includes both pages, portfolio-design.json, builder-defaults.js, and referenced uploads. Existing apps and documents remain in your portfolio folder.'));}
 searchFields();updateJump();}
function searchFields(){const q=$('search').value.trim().toLowerCase();$('fields').querySelectorAll('.field').forEach(n=>n.hidden=!!q&&!n.dataset.search.includes(q));if(q)$('fields').querySelectorAll('details').forEach(n=>{n.open=true;});}
function updateJump(){const old=$('jump').value;$('jump').replaceChildren();const base=el('option','','Jump to section');base.value='';$('jump').append(base);if(page==='home')for(const s of [...extra.sections,...extra.customSections.map(s=>({id:s.id,label:s.heading,enabled:s.enabled}))])if(s.enabled){const o=el('option','',s.label);o.value=s.id;$('jump').append(o);}$('jump').value=old;}
function resize(){const stage=$('preview-stage'),w=width||stage.clientWidth,scale=Math.min(stage.clientWidth/w,1),frame=$('preview');frame.style.width=w+'px';frame.style.height=Math.floor(stage.clientHeight/scale)+'px';frame.style.transform='translateX(-'+w/2+'px) scale('+scale+')';// Center the scaled frame in the available stage.
 frame.style.left=(stage.clientWidth-w*scale)/2+'px';frame.style.transform='scale('+scale+')';$('preview-size').textContent=w+' px · '+Math.round(scale*100)+'%';}
function renderPreview(anchor=''){try{$('preview').srcdoc=G.render(sources[page],state,extra,page,{previews,scrollY:scrolls[page],anchor,base:/^https?:$/.test(location.protocol)?new URL('.',location.href).href:null});previewError=null;$('preview-status').textContent=(dirty?'Preview · unsaved changes':'Your current portfolio')+' · counter paused';resize();}catch(e){previewError=e;$('preview-status').textContent='Preview kept at last valid version · '+e.message;}}
function download(name,content,type='application/octet-stream'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportFiles(){G.validate(state,extra);const home=G.render(sources.home,state,extra,'home'),projects=G.render(sources.projects,state,extra,'projects'),out={};const refs=JSON.stringify({state,extra});for(const[path,file]of pending)if(refs.includes(path))out[path]=file;
 out['index.html']=home;out['projects.html']=projects;out['portfolio-design.json']=JSON.stringify({...state,_studio:extra},null,2)+'\n';const next={version:2,sources:{home,projects},previews};out['builder-defaults.js']='window.PORTFOLIO_DEFAULTS='+C.json(next)+';\n';return out;}
function busyUI(on){busy=on;$('fields').inert=on;for(const id of ['open-folder','save-folder','export-zip','category','search','undo','redo','restore-draft'])$(id).disabled=on;if(!on)buttons();}
function result(title,paragraph,paths=[],backup=null){$('result-title').textContent=title;const root=$('result-body');root.replaceChildren(el('p','',paragraph));if(paths.length){const ul=el('ul','file-list');paths.forEach(p=>ul.append(el('li','',p)));root.append(ul);}if(backup)root.append(el('p','', 'Previous files are backed up in '+backup+'.'));$('result-dialog').showModal();}
async function folderPreviews(){const refs=new Set(state.documents.map(d=>d.preview).concat(state.projects.map(p=>p.image),extra.customSections.map(s=>s.image)));for(const path of refs){if(!path||/^(https?:|data:|blob:)/i.test(path))continue;try{const file=await F.read(session.folder,path);if(file)previews[path]=await dataURL(file);}catch{}}}
async function acceptSources(next,label){G.readState(next.home);G.readState(next.projects);sources=next;state=G.readState(next.home);extra=G.inferExtra(next.home);dirty=false;undo=[];redo=[];pending.clear();checkpoint=snapshot();scrolls={home:0,projects:0};$('source-label').textContent=label;buttons();renderFields();if(session)await folderPreviews();renderPreview();$('draft-status').textContent='Loaded from your files · no unsaved changes';}
async function openFolder(){if(busy)return;if(!window.showDirectoryPicker){toast('Direct folder access needs desktop Chrome or Edge. You can still use Download update ZIP.');return;}if(dirty&&!confirm('Open the folder’s saved pages? Your current edits will remain available as a browser draft.'))return;try{const handle=await showDirectoryPicker({mode:'readwrite',id:'adnan-portfolio'});busyUI(true);if(dirty)await saveDraft();const next=await F.open(handle);G.readState(next.sources.home);G.readState(next.sources.projects);G.inferExtra(next.sources.home);session=next;await acceptSources(next.sources,'Folder: '+handle.name+' · current files');}catch(e){if(e.name!=='AbortError')toast(e.message);}finally{busyUI(false);}}
async function saveFolder(){if(busy)return;try{
 if(!window.showDirectoryPicker){toast('Use Download update ZIP, or open this builder in desktop Chrome or Edge to save directly.');return;}
 if(!session){const h=await showDirectoryPicker({mode:'readwrite',id:'adnan-portfolio'});const opened=await F.open(h);if(opened.sources.home!==sources.home||opened.sources.projects!==sources.projects)throw Error('This folder contains different pages. Use Open portfolio folder to load its current version before saving. Download your design first if you want to keep these edits.');session=opened;}
 else if(await session.folder.queryPermission({mode:'readwrite'})!=='granted'){if(await session.folder.requestPermission({mode:'readwrite'})!=='granted')throw Error('Write access was not granted. Your changes are still in the builder.');}
 busyUI(true);record();const output=exportFiles();const saved=await F.save(session,output,msg=>$('draft-status').textContent=msg);sources={home:output['index.html'],projects:output['projects.html']};dirty=false;pending.clear();$('source-label').textContent='Folder: '+session.folder.name+' · saved';$('draft-status').textContent='Saved to folder · '+new Date().toLocaleTimeString();await clearDraft();$('restore-draft').hidden=true;renderPreview();result('Saved to '+session.folder.name,saved.paths.length?'Your portfolio files and builder defaults are updated. Review, commit, and push with Git.':'The folder already contains these changes.',saved.paths,saved.backup);
 }catch(e){if(e.name!=='AbortError')result('Changes are still in the builder',e.message);}finally{busyUI(false);}}
async function exportZIP(){if(busy)return;try{busyUI(true);record();const files=exportFiles(),zip=new JSZip();for(const[path,file]of Object.entries(files))zip.file(path,file);zip.file('BUILDER-UPDATE.txt','Merge these files into your existing portfolio folder. Keep the existing builder/, apps/, pdfs/, and previews/ folders. Open index-builder.html to continue from these saved defaults.\n');const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});download('portfolio-update.zip',blob);toast('Update ZIP downloaded. Merge its contents into your existing portfolio folder, then commit and push.');}catch(e){result('Export needs attention',e.message);}finally{busyUI(false);}}
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('adnan-portfolio-builder-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});dbPromise.catch(()=>{});
const draftKey=location.pathname;
async function draftOp(mode,action){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode),store=tx.objectStore('drafts'),r=action(store);let value;r.onsuccess=()=>value=r.result;tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function saveDraft(){if(!dirty)return;try{await draftOp('readwrite',store=>store.put({savedAt:new Date().toISOString(),state:clone(state),extra:clone(extra),sources:clone(sources),files:Array.from(pending),previews:clone(previews)},draftKey));$('draft-status').textContent='Browser draft saved · folder changes unsaved';}catch{$('draft-status').textContent='Browser draft unavailable · save to folder or ZIP to keep edits';}}
async function clearDraft(){clearTimeout(draftTimer);try{await draftOp('readwrite',store=>store.delete(draftKey));}catch{}}
$('restore-draft').onclick=async()=>{try{const d=await draftOp('readonly',store=>store.get(draftKey));if(!d)return;if(dirty&&!confirm('Restore the saved browser draft over your current edits?'))return;session=null;sources=d.sources;state=d.state;extra=d.extra;previews=d.previews||previews;pending=new Map(d.files||[]);undo=[];redo=[];checkpoint=snapshot();dirty=true;buttons();renderFields();renderPreview();$('source-label').textContent='Restored browser draft · choose folder to save';$('restore-draft').hidden=true;toast('Draft restored, including uploaded files.');}catch(e){toast(e.message);}};
$('import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const text=await f.text();let value,x;if(text.trim().startsWith('<')){value=G.readState(text);x=G.inferExtra(text);}else{value=JSON.parse(text);x=value._studio||extra;delete value._studio;}G.validate(value,x);mutate(()=>{state=value;extra=x;});toast('Design loaded onto the current pages. Save to folder to apply it.');}catch(err){toast(err.message);}};
$('category').append(...categories.map(([v,name])=>{const o=el('option','',name);o.value=v;return o;}));$('category').onchange=()=>{$('search').value='';renderFields();$('fields').scrollTop=0;};$('search').oninput=searchFields;
$('open-folder').onclick=openFolder;$('save-folder').onclick=saveFolder;$('export-zip').onclick=exportZIP;$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function historyBack(forward=false){record();const from=forward?redo:undo,to=forward?undo:redo;if(!from.length)return;to.push(snapshot());const s=from.pop();state=clone(s.state);extra=clone(s.extra);checkpoint=snapshot();dirty=true;buttons();renderFields();renderPreview();clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,300);}
$('undo').onclick=()=>historyBack();$('redo').onclick=()=>historyBack(true);
$('pages').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;$('pages').querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));updateJump();renderPreview();};$('devices').onclick=e=>{const b=e.target.closest('[data-width]');if(!b)return;width=Number(b.dataset.width);$('devices').querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));resize();};$('reload-preview').onclick=()=>renderPreview();$('jump').onchange=()=>{if($('jump').value)$('preview').contentWindow.postMessage({type:'studio-jump',id:$('jump').value},'*');};
window.addEventListener('message',e=>{if(e.source!==$('preview').contentWindow)return;if(e.data?.type==='studio-scroll'&&['home','projects'].includes(e.data.page))scrolls[e.data.page]=Math.max(0,Number(e.data.y)||0);if(e.data?.type==='studio-link'){const h=e.data.href;if(h==='projects.html'){page='projects';$('pages').querySelector('[data-page=projects]').click();}else if(h==='index.html'||h.startsWith('index.html#')){page='home';$('pages').querySelector('[data-page=home]').click();renderPreview(h.split('#')[1]||'');}else toast('Preview link: '+h+'. Open the saved portfolio to follow external and app links.');}});
window.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='s'){e.preventDefault();saveFolder();}else if(e.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();historyBack(e.shiftKey);}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});new ResizeObserver(resize).observe($('preview-stage'));
async function boot(){renderFields();renderPreview();buttons();try{const draft=await draftOp('readonly',store=>store.get(draftKey));if(draft){$('restore-draft').hidden=false;$('restore-draft').textContent='Restore draft · '+new Date(draft.savedAt).toLocaleString();}}catch{}
 // file:// cannot fetch neighboring HTML. The packaged seed is exact; folder open refreshes it.
 if(/^https?:$/.test(location.protocol)){try{const texts=await Promise.all(['index.html','projects.html'].map(async name=>{const r=await fetch(name,{cache:'no-store'});if(!r.ok)throw Error('Page unavailable');return r.text();}));if(!dirty){await acceptSources({home:texts[0],projects:texts[1]},'Current pages beside this builder');}}catch{/* The exact packaged starting pages remain available. */}}
}
boot();
})();
